import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

/*
import { ChakraProvider } from "@chakra-ui/react";
import Layout from "./components/layouts/main";
import { NextRouter } from 'next/router'; // Import NextRouter type
import './globals.css';
import React from 'react'; // Import React

interface WebsiteProps {
  Component: React.ComponentType<any>; // Use React.ComponentType<any> or a more specific type
  pageProps: any;
  router?: NextRouter; // Make router prop optional
}

function Website({ Component, pageProps, router }: WebsiteProps) {
  // Check if router is defined before accessing its properties
  const route = router?.route;

  return (
    <ChakraProvider>
      <Layout router={router}>
        <Component {...pageProps} key={route} />
      </Layout>
    </ChakraProvider>
  )
}

export default Website;
*/